parameters:
- name: apiurl
  displayName: apiurl
  type: string
- name: artifactName
  displayName: artifactName
  type: string

jobs:
- job: 'buildjob'
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: owaspzap@1
    displayName: Owasp ZAP task
    inputs:
      aggressivemode: true
      threshold: '1000'
      scantype: 'targetedScan'
      url: ${{ parameters.apiurl }}

  - bash: |